### ISSUE TITLE
The keyboard & TouchPad no longer respond in the OC menu after the reboot from the Monterey

### ISSUE THREAD

**Issue by CobanRamo** [CobanRamo/Lenovo-IdeaPad-S340-15IIL#10]
### Discussed in https://github.com/CobanRamo/Lenovo-IdeaPad-S340-15IIL/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **heikebotaru** November  7, 2021</sup>
Hello CobanRamo,
 Thank you for your help the other day. 
When I reboot, the keyboard is not recognised. So I can't type my password. If I press and hold the power button and then boot, the keyboard is recognised. This problem has occurred since I upgraded to Monterey. How is it with your Ideapad?</div>

**Comment by CobanRamo** [comment]
https://github.com/acidanthera/bugtracker/issues/1838

Vit9696 has claimed that it’s a bug of InsydeH2O BIOS for many times. It’s just because Monterey’s brand new way to shutdown makes this bug appear.

**Comment by diepeterpan** [comment]
See https://github.com/acidanthera/bugtracker/issues/1838#issuecomment-1256952124

**Comment by CobanRamo** [comment]
this problem was solved as of VoodooPS2.kext v2.3.1.
