### ISSUE TITLE
Lockups and kernel panics with BCM94360NG WiFi card

### ISSUE THREAD

**Issue by SarenDev** [CobanRamo/Lenovo-IdeaPad-S340-15IIL#12]
I encountered the following issue after swapping the built-in card for a Fenvi one.

When booting normally, Big Sur works for about 2 minutes (wifi and all) and then just freezes. There appears to be no relevant info in the system log.
Booting with `-v` flag causes the OS to either Kernel Panic or lock up after or right before enumerating USB, never getting into the GUI. Kernel panic causes keep changing from boot to boot.
Unplugging the card fixes the problem, and MacOS works perfectly fine.

In troubleshooting, I tried removing the USB map and using the InjectALL kext to no avail.

**Comment by CobanRamo** [comment]
One question; are you using my USB Kext or SSDT?
If so that could be the problem.
I recommend you use your own USB patch under Catalina.

USBInjectall.kext is unusable under BigSur & Monterey.
The best solution is to install Catalina on an apfs volume and enable "XhciPortLimit".
This way you can patch your USB perfectly for your needs.
Attention, from Bigsur 11.3 this way with XhciPortLimit does not work anymore.

Alternatively you can send me your complete ACPI dump (Clover stick F11) and your currently used Efi, I can possibly create a customized USB SSDT for you.

Translated with www.DeepL.com/Translator (free version)

**Comment by SarenDev** [comment]
I was indeed using your SSDT as I assumed it would work since I have the same machine as you do.
I'll try mapping the ports in Catalina then and moving the resulting kext to Big Sur.

**Comment by CobanRamo** [comment]
With a DSDT & SSDT you have to be careful, it is not enough to have the same computer, it can be that you have a different Bios version or also completely different settings activated.

The procedure with my SSDT you can take as a template, simply delete the ports not needed or activate required supplement.

With my EFI starts Windows 10, 11, Linux, MacOS Catalina, BigSur, Monterey and ChromeOS over OpenCore without problems.

The only problem not yet solved is Hibernate Mode 25, Sleep with 0 & 3 works fine.
Monterey creates other problems with keyboard and for my taste not yet mature, I do not yet use it productively.
With Bigsur for example it is like an original MacBook.

**Comment by SarenDev** [comment]
So, unfortunately, removing the existing USB map files and disabling the port limit on Catalina still results in a lockup with the WiFi card installed.
I also tried mapping the ports without the WiFi card and using the resulting kext when booting with the card to no avail.

I wonder if you'd be able to help out based on an ACPI dump that I got from OpenCore: [dsdt.zip](https://github.com/CobanRamo/Lenovo-IdeaPad-S340-15IIL/files/8164886/dsdt.zip)? 
The EFI configuration I'm using is identical to the one on this repo, just with a different SMBIOS serial and now also with the USB maps removed

**Comment by CobanRamo** [comment]
The dump of the OpenCore unfortunately brings nothing, it is also cumbersome to derive something from it.

Look make it simple, take a USB stick format it in GPT style with Fat32 file format, throw in the Clover EFI in the attachment and boot from the USB stick.

The system must not be able to boot (although this efi will probably boot on you).
It's enough if you get clover menu, just press F11 key (you may need fn key depending on your settings).
You should now get a complete proper ACPI dump which is on the stick in the folder Clover/Acpi/Origin.
What I need is this Origin folder to see exactly what is different with your USB ports. Clover can do this much better than OpenCore.
[EFI_Clover.zip](https://github.com/CobanRamo/Lenovo-IdeaPad-S340-15IIL/files/8165116/EFI_Clover.zip)

**Comment by CobanRamo** [comment]
Another thing, please exclude a hardware defect from the card, test this with another card or put the card in another computer whether this only happens with this card.

I have 6 BCM94360NG cards in use here and still no problem discovered as you describe.
It may also not have been installed properly, do you have these problems with Windows?

What is still important with this computer, update the bios to the latest state, bring it to the default settings, go into the debug bios and change ONLY CPU-lock and Graphic DVMT.

Leave everything else on default, believe me, I thought also there you can set a lot of things but it ends with a brick of the laptop and must be restored awkwardly. Has happened to me several times.

You need ONLY the CPU lock & Graphic DVMT, nothing more.

**Comment by CobanRamo** [comment]
So, I compared your ACPI with mine.
It is indeed the same, without any difference.
![compare](https://user-images.githubusercontent.com/68192365/156430103-1cded395-12e4-4451-a48f-32f191bb5a5c.png)

That what is in the original DSDT is also in my built SSDT.

![dsdt](https://user-images.githubusercontent.com/68192365/156430406-3802b389-036e-4d00-896a-0986f2686830.png)

![ssdt](https://user-images.githubusercontent.com/68192365/156430440-0181b2d8-d236-4e2c-aa71-f3a178782302.png)

That would mean that you can use my built SSDT-USB-S340.aml from the repo. This must work.
My computer came with an Intel Wlan card which I replaced with a BCM94360NG.
I don't have an answer at the moment what could be the reason for this, but maybe a defective wlan card.

Try to organize an alternative card to test.

Look you can possibly test also so what, 
sometimes the cards also have ground contact.
Remove the card, cut a plastic film that is 2cm larger than the card and put this film under the card.
![plastic](https://user-images.githubusercontent.com/68192365/156433577-5a18e1a2-b749-48ef-ae15-0e917c97ff84.png)

You can pierce the screw through the foil, the card should not have any contact with the bottom plate. Could solve so problems but that were then already other computers than the Lenovo, a test would not hurt, try it.

**Comment by SarenDev** [comment]
Thanks for looking into this. 

> You can pierce the screw through the foil, the card should not have any contact with the bottom plate. Could solve so problems but that were then already other computers than the Lenovo, a test would not hurt, try it.

Unfortunately, that trick didn't help.

I ordered another card from a different seller and will get back with the results within a couple of weeks.

**Comment by SarenDev** [comment]
I got the new card, and it has the same issue. When testing, I noticed that the macOS cursor becomes visually corrupted when using said new WiFi card; removing it restores everything to normal. Not sure if that helps.

Are there any other troubleshooting steps we can try?

**Comment by CobanRamo** [comment]
Please try to match your bios with these images.
Maybe we can figure out what this could be.

https://github.com/CobanRamo/Lenovo-IdeaPad-S340-15IIL/tree/main/Pictures/Graphic
https://github.com/CobanRamo/Lenovo-IdeaPad-S340-15IIL/tree/main/Pictures/CPU

**Comment by SarenDev** [comment]
> Please try to match your bios with these images.

The only setting I had to adjust was for Total GFX Memory, which did fix the glitched cursor when using the card.

Replacing the EFI with a fresh copy from this repo and testing with the changed BIOS setting didn't resolve the issue

**Comment by CobanRamo** [comment]
if you have everything as in the pictures and there are still problems, there must be something on your device that is different from mine.
I can't explain it any other way...
You are also sure that it is a device with the part number: 81VW00C4GE?

Check it with your device exactly.
https://psref.lenovo.com/Product/IdeaPad/ideapad_S34015IIL

Here with me everything does as it should, have no Graphic Cursor problems, even Wifi with BCM94360NG does its thing.

https://user-images.githubusercontent.com/68192365/158041940-6631d78e-33d8-4ab9-b840-20763fbcbfeb.mp4

**Comment by SarenDev** [comment]
> You are also sure that it is a device with the part number: 81VW00C4GE?

The machine I have isn't exactly the same as yours. Specifically, it's an S340-14IIL (81VV00----), which is identical hardware-wise (and I guess ACPI spec-wise) to your machine, just an inch smaller. Could this all really stem from a difference in models within the same family?

> You have also tried it with all 4 values? 64MB, 96MB, 128MB and 160MB?

I tried all of them. None of them affected the cursor, it stayed perfectly normal, but they also didn't affect the crashing.

> otherwise come here to gitter chat, everyone here has an IceLake, maybe someone will find out what's wrong with your device.

Thank you for the offer; I'll try reaching out on there.

**Comment by CobanRamo** [comment]
> The machine I have isn't exactly the same as yours. Specifically, it's an S340-14IIL (81VV00----), which is identical hardware-wise (and I guess ACPI spec-wise) to your machine, just an inch smaller. Could this all really stem from a difference in models within the same family?

there must really be something else, otherwise I don't understand why it doesn't work for you.
ACPI is the same, apparently there is something that is different for you.

**Comment by SarenDev** [comment]
Since this is probably a hardware problem, I'll close this issue. Thank you for helping look into this!
