### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by SakethKanchi** [CobanRamo/Lenovo-IdeaPad-S340-15IIL#6]
I've been trying to install Mac on this laptop since an year. But haven't been able to. You did it. Can i get your exact files or more clear instructions on what to do to install it.

**Comment by CobanRamo** [comment]
![IMG_0048](https://user-images.githubusercontent.com/68192365/137288620-ae5fde7d-dc04-484b-81de-e95ba12fc99a.jpeg)

**Comment by CobanRamo** [comment]
I don't know this method and have not tested it.
To start the EFI you need a simple USB stick with GPT style (GUID partition style) formatted with Fat32.
In it must be the folder EFI. 
It does not have to be in the ESP/EFI partition, it is enough if it is on a Fat32 formatted partition.

For the MacOS installer this is not enough, it must be created on a HFS+ partition, this is best and fastest done with a MacOS and the Terminal command...
You do not have a MacOS in your environment to create a stick?
This is the best error free method.

**Comment by SakethKanchi** [comment]
Update: I only see the Windows option on the Opencore menu.
![20211014_164729](https://user-images.githubusercontent.com/70198692/137307665-57c4f2a6-ea2e-4949-880a-0530e5b08e05.jpg)

**Comment by SakethKanchi** [comment]
I think the problem is the dmg file. I think it's because of using MacRecovery.py to download the dmg file.... Do you know any alternatives?

**Comment by CobanRamo** [comment]
launch this noname recovery dmg

**Comment by CobanRamo** [comment]
✅VT-D: Disabled --> With my EFI you may leave the enabled.
I solve this problem with the SSDT-DMAC.aml and enable the MacOS compatible virtualization with it.

**Comment by SakethKanchi** [comment]
https://ibb.co/6m6RXSS
https://ibb.co/DtkzMLS
https://ibb.co/QKjN1F0
https://ibb.co/mqvxs03
These are my bios. Should I change anything?

**Comment by CobanRamo** [comment]
![Bildschirmfoto 2021-10-14 um 13 47 33](https://user-images.githubusercontent.com/68192365/137311681-bb688258-e0cb-42dd-846e-2f5ebe7d8320.png)
![Bildschirmfoto 2021-10-14 um 13 48 10](https://user-images.githubusercontent.com/68192365/137311694-23d67bdc-3a16-4d99-9b7c-3e3125ba471a.png)

**Comment by SakethKanchi** [comment]
Thanks.. If the windows method does not work for you.. Then can you post your files.. The dmg files too.. I'm thinking it's because of the dmg file used in opencore method

**Comment by CobanRamo** [comment]
mine is in the middle of the update to Monterey Beta 10, have to be patient a bit so I can test it

**Comment by CobanRamo** [comment]
give me another picture where it stops.

**Comment by SakethKanchi** [comment]
Give me a minute I'll post it

**Comment by CobanRamo** [comment]
sure I can send images, but I have not changed anything in BIOS, only cfg-lock & dvmt.
otherwise I have changed nothing in the debug BIOS, the rest is the same

**Comment by SakethKanchi** [comment]
I've downgraded the BIOS and still got the same error.

**Comment by SakethKanchi** [comment]
Now can you help me do the install.. I'm so excited. But the brightness is really low

**Comment by SakethKanchi** [comment]
> I've already written that to you ... With this method you need the Internet, the 12 GB Intaller will now be reloaded. Yes, I changed my wifi card to a BroadCom. We need to know what kind of card you have built in and whether there is a Kext for this one. If so, you have to include it in the Efi and config.plist. If it is an Intel card you have to see whether it is running in recovery at all, later you have to help with Kext for the Bluetooth. Therefore it can take a while for you ... If you have a USB network card this can help. I'm in a sleep lab here and I can't answer until tomorrow.

Ok for now i'll wait. I have the default wifi card the laptop came with. If you know what i should change in the kexts and config.plis tell me i'll keep trying

**Comment by SakethKanchi** [comment]
Ok so i got everything working. The trackpad click is a bit iffy. i can't use left click
